name: Generate PDF
on:
  release:
    types:
      - published
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Compile with TeXLive
      uses: docker://texlive/texlive:latest
      with:
        entrypoint: latexmk
    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: resume.pdf
